// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE2003:C#", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Factory.AbstractLogger.FormatMessageCallbackFormattedMessage.ToString~System.String")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Factory.AbstractLogger.FormatMessageCallbackFormattedMessage.FormatMessage(System.String,System.Object[])~System.String")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.ConfigurationSectionHandler.ReadConfiguration(System.Xml.XmlNode)~AddUp.CommonLogging.Configuration.LogSetting")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.NoOpLoggerFactoryAdapter.#ctor(AddUp.CommonLogging.Configuration.NameValueCollection)")]
[assembly: SuppressMessage("Minor Code Smell", "S3963:\"static\" fields should be initialized inline", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.#cctor")]
[assembly: SuppressMessage("Critical Code Smell", "S2346:Flags enumerations zero-value members should be named \"None\"", Justification = "<Pending>", Scope = "type", Target = "~T:AddUp.CommonLogging.LogLevel")]
[assembly: SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "<Pending>", Scope = "type", Target = "~T:AddUp.CommonLogging.Configuration.NameValueCollection")]
[assembly: SuppressMessage("Critical Code Smell", "S1994:\"for\" loop increment clauses should modify the loops' counters", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.ExceptionFormatter.Format(System.Exception,System.IFormatProvider)~System.String")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.AssertIsAssignable``1(System.String,System.Type,System.String,System.Object[])~System.Type")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.#cctor")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.Coalesce``1(System.Predicate{``0},``0[])~``0")]
[assembly: SuppressMessage("Style", "IDE0083:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.TryParse``1(``0,System.String)~``0")]
[assembly: SuppressMessage("Maintainability", "CA1510:Use ArgumentNullException throw helper", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.ArgUtils.AssertIsAssignable``1(System.String,System.Type,System.String,System.Object[])~System.Type")]
[assembly: SuppressMessage("Style", "IDE0301:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.NameValueCollection.GetValues(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Configuration.NameValueCollection.GetValues(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.ConfigurationSectionHandler.Create(AddUp.CommonLogging.Configuration.LogSetting,System.Xml.XmlNode)~AddUp.CommonLogging.Configuration.LogSetting")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.ConfigurationSectionHandler.Create(AddUp.CommonLogging.Configuration.LogSetting,System.Xml.XmlNode)~AddUp.CommonLogging.Configuration.LogSetting")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:AddUp.CommonLogging.LogManager.loadLock")]
[assembly: SuppressMessage("Maintainability", "CA1510:Use ArgumentNullException throw helper", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.LogManager.Configure(AddUp.CommonLogging.Configuration.LogConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~P:AddUp.CommonLogging.LogManager.Adapter")]
[assembly: SuppressMessage("Maintainability", "CA1510:Use ArgumentNullException throw helper", Justification = "<Pending>", Scope = "member", Target = "~P:AddUp.CommonLogging.LogManager.Adapter")]
[assembly: SuppressMessage("Maintainability", "CA1510:Use ArgumentNullException throw helper", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.AbstractSimpleLogger.FormatOutput(System.Text.StringBuilder,AddUp.CommonLogging.LogLevel,System.Object,System.Exception)")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.CommonLoggingTraceListener.#ctor(System.Collections.Specialized.NameValueCollection)")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.CommonLoggingTraceListener.#ctor(System.Collections.Specialized.NameValueCollection)")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.CommonLoggingTraceListener.MapLogLevel(System.Diagnostics.TraceEventType)~AddUp.CommonLogging.LogLevel")]
[assembly: SuppressMessage("Style", "IDE0057:Use range operator", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.CommonLoggingTraceListener.GetPropertiesFromInitString(System.String)~System.Collections.Specialized.NameValueCollection")]
[assembly: SuppressMessage("Style", "IDE0078:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.ExceptionFormatter.OutputProperty(System.Reflection.PropertyInfo,System.IFormatProvider,System.Text.StringBuilder,System.Exception)")]
[assembly: SuppressMessage("Style", "IDE0083:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.ExceptionFormatter.OutputProperty(System.Reflection.PropertyInfo,System.IFormatProvider,System.Text.StringBuilder,System.Exception)")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.TraceLogger.Map2TraceEventType(AddUp.CommonLogging.LogLevel)~System.Diagnostics.TraceEventType")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.TraceLogger.Map2SourceLevel(AddUp.CommonLogging.LogLevel)~System.Diagnostics.SourceLevels")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:AddUp.CommonLogging.Simple.TraceLogger.FormatOutputMessage.#ctor(AddUp.CommonLogging.Simple.TraceLogger,AddUp.CommonLogging.LogLevel,System.Object,System.Exception)")]
